#!/usr/bin/env -S uv run --script
#
# /// script
# dependencies = [
#   "urwid",
#   "typing_extensions",
#   "pyperclip",
#   "urwid",
#   "platformdirs",
# ]
# ///


from __future__ import annotations

import hashlib
import re
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING, ClassVar, cast

import pyperclip
import urwid
from platformdirs import user_cache_dir
from typing_extensions import override


if TYPE_CHECKING:
    from collections.abc import Sequence


def transform(s: str):
    def replace_entity(match: re.Match[str]):
        from html.entities import name2codepoint

        try:
            return chr(name2codepoint[match.group(1)])
        except KeyError:
            return match.group(0)

    s = re.sub(r"(?<!\\)\\([A-Za-z0-9]+)\;?", replace_entity, s)

    return s


@dataclass
class CharInfo:
    names: Sequence[str]
    groups: Sequence[str]
    codepoint: int
    crossrefs: Sequence[str]
    unichar: str = ""

    search_names: Sequence[str] = ()

    def __post_init__(self):
        self.unichar = chr(self.codepoint)
        self.search_names = [
                name.lower() for name in self.names
            ] + [
                grp.lower() for grp in self.groups
            ]


def read_names_list():
    result: list[CharInfo] = []

    import gzip
    from os.path import exists

    url = "http://www.unicode.org/Public/6.1.0/ucd/NamesList.txt"
    url_hash = hashlib.sha256(url.encode()).hexdigest()[:8]
    cache_dir = Path(user_cache_dir("uih", "andreas"))
    cache_dir.mkdir(parents=True, exist_ok=True)
    namelist_filename = cache_dir / f"NamesList_{url_hash}.txt.gz"

    if not exists(namelist_filename):
        print("one second... fetching unicode names list...")
        from urllib.request import urlopen

        nl = urlopen(url).read()
        with gzip.open(namelist_filename, "w") as outf:
            outf.write(nl)

    with gzip.open(namelist_filename, "r") as inf:
        uncompressed_nl = inf.read().decode("utf-8", errors="replace")

    lines = uncompressed_nl.split("\n")
    while not lines[-1]:
        lines.pop()

    it = iter(enumerate(lines))

    hex_set = "0123456789ABCDEF"
    whitespace = " \t"

    print("one second... reading unicode names list...")
    current_group = ""
    try:
        lineno, ln = next(it)

        while True:
            assert ln
            if ln[0] == "@":
                words = ln.split()
                if words[0] == "@":
                    current_group = " ".join(words[1:])
                    lineno, ln = next(it)
                elif words[0].endswith("+"):
                    while True:
                        lineno, ln = next(it)
                        if ln[0] not in whitespace:
                            break
                else:
                    lineno, ln = next(it)
            elif ln[0] in whitespace:
                lineno, ln = next(it)
            elif ln[0] in hex_set:
                words = ln.split()
                codepoint = int(words[0], base=16)
                names = [" ".join(words[1:])]
                crossrefs: list[str] = []
                # print(hex(codepoint), names[0])

                while True:
                    lineno, ln = next(it)

                    if ln[0] not in whitespace:
                        break

                    words = ln.split()
                    if words[0] in ["=", "%"]:
                        names.append(" ".join(words[1:]))
                    elif words[0] in ["x"]:
                        crossrefs.append(" ".join(words[1:]))
                    elif words[0] in ["*", "#", ":"]:
                        pass  # ignore
                    else:
                        raise ValueError(
                            "parsing unicode names list: not sure what "
                            "to do with line %d" % (lineno + 1)
                        )
                result.append(
                    CharInfo(
                        names=names,
                        groups=[current_group],
                        codepoint=codepoint,
                        crossrefs=crossrefs,
                    )
                )
            else:
                raise ValueError(
                    "parsing unicode names list: not sure "
                    "what to do with line %d" % (lineno + 1)
                )

    except StopIteration:
        pass

    return result


names_list = read_names_list()


class UniCharWidget(urwid.Widget):
    _sizing: ClassVar[frozenset[urwid.Sizing]] = frozenset([urwid.Sizing.FLOW])

    char_info: CharInfo
    collapsed: bool = True

    def __init__(self, char_info: CharInfo):
        self.char_info = char_info
        self.collapsed = True
        super().__init__()

    @override
    def selectable(self):
        return True

    @override
    def rows(self, maxcol_tup: tuple[int], focus: bool = False):
        return 1

    def _make_canvas(self, text: str, attr_str: str, maxcol: int):
        attr = [
            (attr_str, len(text)),
        ]

        diff = maxcol - len(text)
        if diff > 0:
            text += " " * diff
            attr.append((attr_str, diff))
        else:
            from urwid.util import rle_subseg

            text = text[:maxcol]
            attr = rle_subseg(attr, 0, maxcol)

        from urwid.util import apply_target_encoding

        txt, cs = apply_target_encoding(text)

        return urwid.TextCanvas([txt], [attr], [cs], maxcol=maxcol)

    @override
    def render(self, maxcol_tup: tuple[int], focus: bool = False):
        (maxcol,) = maxcol_tup
        apfx = "focused " if focus else ""

        attr = apfx + "unichar"

        try:
            from unicodedata import combining

            uchar = self.char_info.unichar
            if combining(uchar):
                uchar = "A" + uchar
            return self._make_canvas(
                uchar + " " + self.char_info.names[0], attr, maxcol
            )
        except urwid.canvas.CanvasError:
            return self._make_canvas("(ERROR) " + self.char_info.names[0], attr, maxcol)

    @override
    def keypress(self, size, key):
        return key


def get_uc_list(filter_expr: str):
    words = [word for word in filter_expr.lower().split() if word]

    last_group = None

    result: list[urwid.Widget] = []

    for ci in names_list:
        match = True
        for word in words:
            if not any(word in sn for sn in ci.search_names):
                match = False
                break

        if match:
            if ord(ci.unichar) < 32:
                continue

            cigrp = ci.groups[0]
            if cigrp != last_group:
                result.append(
                    urwid.AttrMap(
                        urwid.Text(" - %s -" % cigrp),
                        "group header",
                        "focused group header",
                    )
                )

            result.append(UniCharWidget(ci))

            last_group = cigrp

    return result


def show_overlay(loop: urwid.MainLoop, message: str):
    """Briefly show a message overlay."""
    old_widget = loop.widget
    text = urwid.Text(f"\n {message} \n", align="center")
    fill = urwid.Filler(urwid.LineBox(text))
    overlay = urwid.Overlay(
        fill, old_widget, "center", ("relative", 60), "middle", ("relative", 20)
    )

    def remove_overlay(loop: urwid.MainLoop, data):
        loop.widget = old_widget

    loop.widget = overlay
    loop.set_alarm_in(1.5, remove_overlay)


def run(loop_list: list[urwid.MainLoop]):
    pre = urwid.Edit()
    pre_wrap = urwid.AttrMap(pre, "input")
    post = urwid.Text("")

    uc_filt = urwid.Edit()
    uc_filt_wrap = urwid.AttrMap(uc_filt, "input")
    uc_list_walker = urwid.SimpleListWalker([])

    uc_listbox = urwid.ListBox(uc_list_walker)
    uc_list_wrap = urwid.AttrMap(uc_listbox, "input")

    def copy_to_clipboard(_button: urwid.Button):
        loop, = loop_list
        show_overlay(loop, "Copied to clipboard")
        pyperclip.copy(cast("str", post.text))

    copy_button = urwid.Button("Copy", on_press=copy_to_clipboard)
    copy_button_wrap = urwid.AttrWrap(copy_button, "input")

    # Connect signals for reactive updates
    def on_pre_change(widget, new_value):
        post.set_text(transform(new_value))

    urwid.connect_signal(pre, "change", on_pre_change)

    def on_filt_change(widget, new_value):
        uc_list_walker[:] = get_uc_list(new_value)

    urwid.connect_signal(uc_filt, "change", on_filt_change)

    class MainPile(urwid.Pile):
        @override
        def keypress(self, size, key):
            if key == "esc":
                raise urwid.ExitMainLoop()
            elif key == "+":
                if self.focus == uc_list_wrap:
                    ucw = uc_listbox.focus
                    if ucw is not None:
                        pre.insert_text(ucw.char_info.unichar)
                    return None
            elif key == "enter":
                if self.focus == uc_list_wrap:
                    ucw = uc_listbox.focus
                    if ucw is not None:
                        pre.insert_text(ucw.char_info.unichar)
                    self.focus = pre_wrap
                    return None
                elif self.focus == uc_filt_wrap:
                    self.focus = uc_list_wrap
                    return None
            elif key == "tab":
                if self.focus == uc_list_wrap:
                    self.focus = pre_wrap
                elif self.focus == pre_wrap:
                    self.focus = uc_list_wrap
                return None
            elif key == "ctrl u":
                copy_to_clipboard(copy_button)
            elif key == "f":
                if self.focus == uc_list_wrap:
                    self.focus = uc_filt_wrap
                return None

            return super().keypress(size, key)

    main_pile = MainPile([
        (
            "flow",
            urwid.AttrMap(
                urwid.Text(
                    "Mathy Unicode Input Helper (C) Andreas Kloeckner 2009",
                    align="center",
                ),
                "title",
            ),
        ),
        ("fixed", 1, urwid.SolidFill()),
        ("flow", urwid.Text("Text to transform?")),
        ("flow", pre_wrap),
        ("flow", urwid.Text("Transformed text:")),
        ("flow", urwid.Columns([
            ("weight", 1, urwid.AttrMap(post, "result")),
            ("fixed", 10, copy_button_wrap),
        ])),
        ("fixed", 1, urwid.SolidFill()),
        ("flow", urwid.Text("Filter for list of Unicode characters:")),
        ("flow", uc_filt_wrap),
        ("fixed", 1, urwid.SolidFill()),
        ("weight", 1, uc_list_wrap),
        ("fixed", 1, urwid.SolidFill()),
        ("flow", urwid.Text("^u: copy transformed text | esc: exit")),
    ])

    w = urwid.AttrMap(
        urwid.Columns([
            ("fixed", 1, urwid.SolidFill()),
            main_pile,
            ("fixed", 1, urwid.SolidFill()),
        ]),
        "background",
    )

    # Initialize list
    uc_list_walker[:] = get_uc_list(uc_filt.get_edit_text())

    return w, pre


def main():
    loop_list = []
    w, pre = run(loop_list)

    loop = urwid.MainLoop(
        w,
        screen=urwid.curses_display.Screen(),
        palette=[
            ("input", "black", "dark cyan"),
            ("background", "black", "light gray"),
            ("result", "light gray", "black"),
            ("title", "white", "dark blue"),
            ("unichar", "black", "dark cyan"),
            ("focused unichar", "black", "dark green"),
            ("group header", "light gray", "dark cyan"),
            ("focused group header", "light gray", "dark green"),
        ],
    )
    loop_list[:] = [loop]

    loop.run()

    pre_text = pre.get_edit_text()
    post_text = transform(pre_text)

    print("Untransformed:")
    print("  ", pre_text)
    print("Transformed:")
    print("  ", post_text)


if __name__ == "__main__":
    main()
